export const SET_SORT_ORDER = 'SET_SORT_ORDER';
export const SET_TYPES_TO_DISPLAY = 'SET_TYPES_TO_DISPLAY';
export const SET_GI_RANGE = 'SET_GI_RANGE';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SET_GI_TARGET = 'SET_GI_TARGET';
export const UPDATE_WEEK = 'UPDATE_WEEK';
